#!/usr/bin/env python3

import google.generativeai as genai
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv('.env.gmail')

def create_nano_banana_logos():
    """Use Nano Banana Pro to generate forest green logo concepts"""
    
    api_key = os.getenv('GOOGLE_API_KEY')
    if not api_key:
        print("❌ Missing Google API key")
        return
    
    genai.configure(api_key=api_key)
    
    try:
        model = genai.GenerativeModel('nano-banana-pro-preview')
        
        prompt = """
I need 10 professional logo concepts for "LEMMIK CONSTRUCTION RECRUITING" in forest green.

Reference style: Clean, geometric, minimalist design with simple shapes inside a circle (like the building silhouette bars in a circle I showed you).

Requirements:
- Forest green color (#1E5128) 
- Simple, clean geometric shapes
- Construction/recruiting industry relevant
- Circular framing for consistency
- Minimalist, professional aesthetic
- Each concept should be distinctly different

For each of the 10 concepts, provide:
1. Concept name and theme
2. Detailed visual description (exact shapes, positioning, proportions)
3. Why it works for construction recruiting
4. Professional appeal and target audience

Make them sophisticated but simple - think Fortune 500 company logos, not complex illustrations.

Concepts should include themes like:
- Construction tools/equipment
- Building/structural elements  
- Growth/progress symbols
- Connection/networking symbols
- Precision/quality indicators
- Industrial/engineering elements

Each description should be detailed enough that a designer could create the exact logo from your description.
        """
        
        print("🍌 Using Nano Banana Pro for 10 Forest Green Logo Concepts...")
        print("🌲 Generating sophisticated, professional designs...")
        print("=" * 70)
        
        response = model.generate_content(prompt)
        
        print(response.text)
        print("=" * 70)
        print("✅ Nano Banana Pro logo concepts complete!")
        
        # Save the concepts to a file
        with open('nano_banana_logo_concepts.md', 'w') as f:
            f.write("# LEMMIK CONSTRUCTION RECRUITING - LOGO CONCEPTS\n")
            f.write("## Generated by Nano Banana Pro AI\n\n")
            f.write(response.text)
        
        print("📁 Concepts saved to: nano_banana_logo_concepts.md")
        
        return response.text
        
    except Exception as e:
        print(f"❌ Error with Nano Banana Pro: {e}")
        return None

if __name__ == "__main__":
    create_nano_banana_logos()